### PR TITLE
updated winner,loser,inconclusive icons 24px

### PR DESCRIPTION
**Pull request by nehasaigal1**
@danoc @tscanlin

### CODE REVIEW

**Comment by tscanlin** [comment]
Did you update the 16px too?

**Comment by danoc** [comment]
Just a note to myself @tscanlin that we need to update the change log before merging.

**Comment by danoc** [comment]
@nehasaigal1 will be updating this to include the 16px version of the icons. Let's wait until that is up to merge.

**Comment by tscanlin** [comment]
@nehasaigal1 are the 16px versions ready yet? No worries if not, just let me know when you have an ETA. Thanks!

**Comment by tscanlin** [comment]
@nehasaigal1 are you still working on these icons?

**Pull request closed without merging**
